//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnDemo.Form.FormAdmin
{
    partial class FormSanPham
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            this.splitContainerMain = new System.Windows.Forms.SplitContainer();
            this.panelDanhSach = new System.Windows.Forms.Panel();
            this.dgvDanhSachSanPham = new System.Windows.Forms.DataGridView();
            this.maSanPhamCol = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.tenSanPhamCol = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.danhMucCol = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.giaKhuyenNghiCol = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.donViTinhCol = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.trangThaiChungCol = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.panelTimKiem = new System.Windows.Forms.Panel();
            this.btnLamMoiDanhSach = new System.Windows.Forms.Button();
            this.btnTimKiem = new System.Windows.Forms.Button();
            this.cboLocTrangThai = new System.Windows.Forms.ComboBox();
            this.label3 = new System.Windows.Forms.Label();
            this.cboLocDanhMuc = new System.Windows.Forms.ComboBox();
            this.label2 = new System.Windows.Forms.Label();
            this.txtTimKiem = new System.Windows.Forms.TextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.gbChiTietSanPham = new System.Windows.Forms.GroupBox();
            this.btnChonAnh = new System.Windows.Forms.Button();
            this.picHinhAnhSanPham = new System.Windows.Forms.PictureBox();
            this.txtHinhAnhUrl = new System.Windows.Forms.TextBox();
            this.label13 = new System.Windows.Forms.Label();
            this.txtNgayCapNhat = new System.Windows.Forms.TextBox();
            this.label12 = new System.Windows.Forms.Label();
            this.txtNgayTao = new System.Windows.Forms.TextBox();
            this.label11 = new System.Windows.Forms.Label();
            this.radInactive = new System.Windows.Forms.RadioButton();
            this.radActive = new System.Windows.Forms.RadioButton();
            this.label10 = new System.Windows.Forms.Label();
            this.cboDonViTinh = new System.Windows.Forms.ComboBox();
            this.label9 = new System.Windows.Forms.Label();
            this.numGiaKhuyenNghi = new System.Windows.Forms.NumericUpDown();
            this.label8 = new System.Windows.Forms.Label();
            this.cboDanhMuc = new System.Windows.Forms.ComboBox();
            this.label7 = new System.Windows.Forms.Label();
            this.txtMoTa = new System.Windows.Forms.TextBox();
            this.label6 = new System.Windows.Forms.Label();
            this.txtTenSanPham = new System.Windows.Forms.TextBox();
            this.label5 = new System.Windows.Forms.Label();
            this.txtMaSanPham = new System.Windows.Forms.TextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.txtIdSanPham = new System.Windows.Forms.TextBox();
            this.lblId = new System.Windows.Forms.Label();
            this.panelNutChucNang = new System.Windows.Forms.Panel();
            this.btnBoQua = new System.Windows.Forms.Button();
            this.btnXoa = new System.Windows.Forms.Button();
            this.btnLuu = new System.Windows.Forms.Button();
            this.btnThemMoi = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainerMain)).BeginInit();
            this.splitContainerMain.Panel1.SuspendLayout();
            this.splitContainerMain.Panel2.SuspendLayout();
            this.splitContainerMain.SuspendLayout();
            this.panelDanhSach.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDanhSachSanPham)).BeginInit();
            this.panelTimKiem.SuspendLayout();
            this.gbChiTietSanPham.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picHinhAnhSanPham)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numGiaKhuyenNghi)).BeginInit();
            this.panelNutChucNang.SuspendLayout();
            this.SuspendLayout();
            // 
            // splitContainerMain
            // 
            this.splitContainerMain.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240))))); // Style Change: Nền chính
            this.splitContainerMain.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainerMain.Location = new System.Drawing.Point(0, 0);
            this.splitContainerMain.Name = "splitContainerMain";
            // 
            // splitContainerMain.Panel1
            // 
            this.splitContainerMain.Panel1.BackColor = System.Drawing.Color.White; // Style Change: Nền Panel trái
            this.splitContainerMain.Panel1.Controls.Add(this.panelDanhSach);
            this.splitContainerMain.Panel1.Controls.Add(this.panelTimKiem);
            this.splitContainerMain.Panel1MinSize = 400;
            // 
            // splitContainerMain.Panel2
            // 
            this.splitContainerMain.Panel2.BackColor = System.Drawing.Color.White; // Style Change: Nền Panel phải
            this.splitContainerMain.Panel2.Controls.Add(this.gbChiTietSanPham);
            this.splitContainerMain.Panel2.Controls.Add(this.panelNutChucNang);
            this.splitContainerMain.Panel2MinSize = 450;
            this.splitContainerMain.Size = new System.Drawing.Size(1100, 650);
            this.splitContainerMain.SplitterDistance = 550;
            this.splitContainerMain.SplitterWidth = 6; // Style Change: Tăng độ rộng splitter
            this.splitContainerMain.TabIndex = 0;
            // 
            // panelDanhSach
            // 
            this.panelDanhSach.Controls.Add(this.dgvDanhSachSanPham);
            this.panelDanhSach.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panelDanhSach.Location = new System.Drawing.Point(0, 80);
            this.panelDanhSach.Name = "panelDanhSach";
            this.panelDanhSach.Padding = new System.Windows.Forms.Padding(5);
            this.panelDanhSach.Size = new System.Drawing.Size(550, 570);
            this.panelDanhSach.TabIndex = 1;
            // 
            // dgvDanhSachSanPham
            // 
            this.dgvDanhSachSanPham.AllowUserToAddRows = false;
            this.dgvDanhSachSanPham.AllowUserToDeleteRows = false;
            this.dgvDanhSachSanPham.AllowUserToResizeRows = false; // Style Change
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(245)))), ((int)(((byte)(250))))); // Style Change: Màu dòng xen kẽ
            this.dgvDanhSachSanPham.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dgvDanhSachSanPham.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill; // Style Change: Tự giãn cột
            this.dgvDanhSachSanPham.BackgroundColor = System.Drawing.Color.White; // Style Change
            this.dgvDanhSachSanPham.BorderStyle = System.Windows.Forms.BorderStyle.None; // Style Change
            this.dgvDanhSachSanPham.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal; // Style Change
            this.dgvDanhSachSanPham.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None; // Style Change
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(130)))), ((int)(((byte)(180))))); // Style Change: Màu header (SteelBlue)
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold); // Style Change: Font header
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White; // Style Change: Chữ header
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(70)))), ((int)(((byte)(130)))), ((int)(((byte)(180))))); // Style Change
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvDanhSachSanPham.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dgvDanhSachSanPham.ColumnHeadersHeight = 40; // Style Change: Chiều cao header
            this.dgvDanhSachSanPham.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.dgvDanhSachSanPham.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.maSanPhamCol,
            this.tenSanPhamCol,
            this.danhMucCol,
            this.giaKhuyenNghiCol,
            this.donViTinhCol,
            this.trangThaiChungCol});
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.SystemColors.Window;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI", 9F); // Style Change: Font dòng
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64))))); // Style Change: Màu chữ dòng
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(173)))), ((int)(((byte)(216)))), ((int)(((byte)(230))))); // Style Change: Màu chọn dòng (LightBlue)
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64))))); // Style Change: Màu chữ chọn dòng
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvDanhSachSanPham.DefaultCellStyle = dataGridViewCellStyle3;
            this.dgvDanhSachSanPham.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dgvDanhSachSanPham.EnableHeadersVisualStyles = false; // Style Change: Quan trọng để áp dụng style header
            this.dgvDanhSachSanPham.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224))))); // Style Change: Màu đường kẻ
            this.dgvDanhSachSanPham.Location = new System.Drawing.Point(5, 5);
            this.dgvDanhSachSanPham.MultiSelect = false;
            this.dgvDanhSachSanPham.Name = "dgvDanhSachSanPham";
            this.dgvDanhSachSanPham.ReadOnly = true;
            this.dgvDanhSachSanPham.RowHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None; // Style Change
            this.dgvDanhSachSanPham.RowHeadersVisible = false; // Style Change: Ẩn header dòng
            this.dgvDanhSachSanPham.RowHeadersWidth = 51;
            this.dgvDanhSachSanPham.RowTemplate.Height = 35; // Style Change: Chiều cao dòng
            this.dgvDanhSachSanPham.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvDanhSachSanPham.Size = new System.Drawing.Size(540, 560);
            this.dgvDanhSachSanPham.TabIndex = 0;
            // 
            // maSanPhamCol
            // 
            this.maSanPhamCol.DataPropertyName = "MaSanPham";
            this.maSanPhamCol.FillWeight = 80F; // Điều chỉnh tỉ lệ fill
            this.maSanPhamCol.HeaderText = "Mã SP";
            this.maSanPhamCol.MinimumWidth = 6;
            this.maSanPhamCol.Name = "maSanPhamCol";
            this.maSanPhamCol.ReadOnly = true;
            // 
            // tenSanPhamCol
            // 
            this.tenSanPhamCol.DataPropertyName = "TenSanPham";
            this.tenSanPhamCol.FillWeight = 150F; // Điều chỉnh tỉ lệ fill
            this.tenSanPhamCol.HeaderText = "Tên Sản Phẩm";
            this.tenSanPhamCol.MinimumWidth = 6;
            this.tenSanPhamCol.Name = "tenSanPhamCol";
            this.tenSanPhamCol.ReadOnly = true;
            // 
            // danhMucCol
            // 
            this.danhMucCol.DataPropertyName = "DanhMuc";
            this.danhMucCol.FillWeight = 90F; // Điều chỉnh tỉ lệ fill
            this.danhMucCol.HeaderText = "Danh Mục";
            this.danhMucCol.MinimumWidth = 6;
            this.danhMucCol.Name = "danhMucCol";
            this.danhMucCol.ReadOnly = true;
            // 
            // giaKhuyenNghiCol
            // 
            this.giaKhuyenNghiCol.DataPropertyName = "GiaKhuyenNghi";
            dataGridViewCellStyle4.Format = "N0"; // Style Change: Format số không có phần thập phân
            dataGridViewCellStyle4.NullValue = null;
            this.giaKhuyenNghiCol.DefaultCellStyle = dataGridViewCellStyle4;
            this.giaKhuyenNghiCol.FillWeight = 80F; // Điều chỉnh tỉ lệ fill
            this.giaKhuyenNghiCol.HeaderText = "Giá KN";
            this.giaKhuyenNghiCol.MinimumWidth = 6;
            this.giaKhuyenNghiCol.Name = "giaKhuyenNghiCol";
            this.giaKhuyenNghiCol.ReadOnly = true;
            // 
            // donViTinhCol
            // 
            this.donViTinhCol.DataPropertyName = "DonViTinh";
            this.donViTinhCol.FillWeight = 60F; // Điều chỉnh tỉ lệ fill
            this.donViTinhCol.HeaderText = "ĐVT";
            this.donViTinhCol.MinimumWidth = 6;
            this.donViTinhCol.Name = "donViTinhCol";
            this.donViTinhCol.ReadOnly = true;
            // 
            // trangThaiChungCol
            // 
            this.trangThaiChungCol.DataPropertyName = "TrangThaiChung";
            this.trangThaiChungCol.FillWeight = 70F; // Điều chỉnh tỉ lệ fill
            this.trangThaiChungCol.HeaderText = "Trạng Thái";
            this.trangThaiChungCol.MinimumWidth = 6;
            this.trangThaiChungCol.Name = "trangThaiChungCol";
            this.trangThaiChungCol.ReadOnly = true;
            // 
            // panelTimKiem
            // 
            this.panelTimKiem.BackColor = System.Drawing.Color.White; // Style Change
            this.panelTimKiem.Controls.Add(this.btnLamMoiDanhSach);
            this.panelTimKiem.Controls.Add(this.btnTimKiem);
            this.panelTimKiem.Controls.Add(this.cboLocTrangThai);
            this.panelTimKiem.Controls.Add(this.label3);
            this.panelTimKiem.Controls.Add(this.cboLocDanhMuc);
            this.panelTimKiem.Controls.Add(this.label2);
            this.panelTimKiem.Controls.Add(this.txtTimKiem);
            this.panelTimKiem.Controls.Add(this.label1);
            this.panelTimKiem.Dock = System.Windows.Forms.DockStyle.Top;
            this.panelTimKiem.Location = new System.Drawing.Point(0, 0);
            this.panelTimKiem.Name = "panelTimKiem";
            this.panelTimKiem.Size = new System.Drawing.Size(550, 80);
            this.panelTimKiem.TabIndex = 0;
            // 
            // btnLamMoiDanhSach
            // 
            this.btnLamMoiDanhSach.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(83)))), ((int)(((byte)(79))))); // Style Change: Màu khác (đỏ nhẹ)
            this.btnLamMoiDanhSach.FlatAppearance.BorderSize = 0; // Style Change
            this.btnLamMoiDanhSach.FlatStyle = System.Windows.Forms.FlatStyle.Flat; // Style Change
            this.btnLamMoiDanhSach.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold); // Style Change
            this.btnLamMoiDanhSach.ForeColor = System.Drawing.Color.White; // Style Change
            this.btnLamMoiDanhSach.Location = new System.Drawing.Point(450, 40);
            this.btnLamMoiDanhSach.Name = "btnLamMoiDanhSach";
            this.btnLamMoiDanhSach.Size = new System.Drawing.Size(85, 30);
            this.btnLamMoiDanhSach.TabIndex = 7;
            this.btnLamMoiDanhSach.Text = "Làm mới";
            this.btnLamMoiDanhSach.UseVisualStyleBackColor = false; // Style Change
            // 
            // btnTimKiem
            // 
            this.btnTimKiem.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(184)))), ((int)(((byte)(92))))); // Style Change: Màu khác (xanh lá)
            this.btnTimKiem.FlatAppearance.BorderSize = 0; // Style Change
            this.btnTimKiem.FlatStyle = System.Windows.Forms.FlatStyle.Flat; // Style Change
            this.btnTimKiem.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold); // Style Change
            this.btnTimKiem.ForeColor = System.Drawing.Color.White; // Style Change
            this.btnTimKiem.Location = new System.Drawing.Point(450, 8);
            this.btnTimKiem.Name = "btnTimKiem";
            this.btnTimKiem.Size = new System.Drawing.Size(85, 30);
            this.btnTimKiem.TabIndex = 6;
            this.btnTimKiem.Text = "Tìm kiếm";
            this.btnTimKiem.UseVisualStyleBackColor = false; // Style Change
            // 
            // cboLocTrangThai
            // 
            this.cboLocTrangThai.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboLocTrangThai.Font = new System.Drawing.Font("Segoe UI", 9F); // Style Change
            this.cboLocTrangThai.FormattingEnabled = true;
            this.cboLocTrangThai.Location = new System.Drawing.Point(290, 45);
            this.cboLocTrangThai.Name = "cboLocTrangThai";
            this.cboLocTrangThai.Size = new System.Drawing.Size(145, 28); // Style Change: Cập nhật chiều cao
            this.cboLocTrangThai.TabIndex = 5;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Segoe UI", 9F); // Style Change
            this.label3.Location = new System.Drawing.Point(215, 48);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(78, 20); // Style Change: Cập nhật kích thước
            this.label3.TabIndex = 4;
            this.label3.Text = "Trạng thái:";
            // 
            // cboLocDanhMuc
            // 
            this.cboLocDanhMuc.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboLocDanhMuc.Font = new System.Drawing.Font("Segoe UI", 9F); // Style Change
            this.cboLocDanhMuc.FormattingEnabled = true;
            this.cboLocDanhMuc.Location = new System.Drawing.Point(85, 45);
            this.cboLocDanhMuc.Name = "cboLocDanhMuc";
            this.cboLocDanhMuc.Size = new System.Drawing.Size(120, 28); // Style Change: Cập nhật chiều cao
            this.cboLocDanhMuc.TabIndex = 3;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Segoe UI", 9F); // Style Change
            this.label2.Location = new System.Drawing.Point(10, 48);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(78, 20); // Style Change: Cập nhật kích thước
            this.label2.TabIndex = 2;
            this.label2.Text = "Danh mục:";
            // 
            // txtTimKiem
            // 
            this.txtTimKiem.Font = new System.Drawing.Font("Segoe UI", 9F); // Style Change
            this.txtTimKiem.Location = new System.Drawing.Point(85, 12);
            this.txtTimKiem.Name = "txtTimKiem";
            this.txtTimKiem.Size = new System.Drawing.Size(350, 27); // Style Change: Cập nhật chiều cao
            this.txtTimKiem.TabIndex = 1;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Segoe UI", 9F); // Style Change
            this.label1.Location = new System.Drawing.Point(10, 15);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(73, 20); // Style Change: Cập nhật kích thước
            this.label1.TabIndex = 0;
            this.label1.Text = "Tìm kiếm:";
            // 
            // gbChiTietSanPham
            // 
            this.gbChiTietSanPham.BackColor = System.Drawing.Color.White; // Style Change
            this.gbChiTietSanPham.Controls.Add(this.btnChonAnh);
            this.gbChiTietSanPham.Controls.Add(this.picHinhAnhSanPham);
            this.gbChiTietSanPham.Controls.Add(this.txtHinhAnhUrl);
            this.gbChiTietSanPham.Controls.Add(this.label13);
            this.gbChiTietSanPham.Controls.Add(this.txtNgayCapNhat);
            this.gbChiTietSanPham.Controls.Add(this.label12);
            this.gbChiTietSanPham.Controls.Add(this.txtNgayTao);
            this.gbChiTietSanPham.Controls.Add(this.label11);
            this.gbChiTietSanPham.Controls.Add(this.radInactive);
            this.gbChiTietSanPham.Controls.Add(this.radActive);
            this.gbChiTietSanPham.Controls.Add(this.label10);
            this.gbChiTietSanPham.Controls.Add(this.cboDonViTinh);
            this.gbChiTietSanPham.Controls.Add(this.label9);
            this.gbChiTietSanPham.Controls.Add(this.numGiaKhuyenNghi);
            this.gbChiTietSanPham.Controls.Add(this.label8);
            this.gbChiTietSanPham.Controls.Add(this.cboDanhMuc);
            this.gbChiTietSanPham.Controls.Add(this.label7);
            this.gbChiTietSanPham.Controls.Add(this.txtMoTa);
            this.gbChiTietSanPham.Controls.Add(this.label6);
            this.gbChiTietSanPham.Controls.Add(this.txtTenSanPham);
            this.gbChiTietSanPham.Controls.Add(this.label5);
            this.gbChiTietSanPham.Controls.Add(this.txtMaSanPham);
            this.gbChiTietSanPham.Controls.Add(this.label4);
            this.gbChiTietSanPham.Controls.Add(this.txtIdSanPham);
            this.gbChiTietSanPham.Controls.Add(this.lblId);
            this.gbChiTietSanPham.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gbChiTietSanPham.Font = new System.Drawing.Font("Segoe UI Semibold", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0))); // Style Change: Font GroupBox
            this.gbChiTietSanPham.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(71)))), ((int)(((byte)(160))))); // Style Change: Màu chữ tiêu đề GroupBox (Dark Blue)
            this.gbChiTietSanPham.Location = new System.Drawing.Point(0, 0);
            this.gbChiTietSanPham.Name = "gbChiTietSanPham";
            this.gbChiTietSanPham.Padding = new System.Windows.Forms.Padding(10, 10, 10, 5);
            this.gbChiTietSanPham.Size = new System.Drawing.Size(540, 600);
            this.gbChiTietSanPham.TabIndex = 0;
            this.gbChiTietSanPham.TabStop = false;
            this.gbChiTietSanPham.Text = "Thông tin chi tiết sản phẩm";
            // 
            // btnChonAnh
            // 
            this.btnChonAnh.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(173)))), ((int)(((byte)(78))))); // Style Change: Màu khác (vàng cam)
            this.btnChonAnh.FlatAppearance.BorderSize = 0; // Style Change
            this.btnChonAnh.FlatStyle = System.Windows.Forms.FlatStyle.Flat; // Style Change
            this.btnChonAnh.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold); // Style Change
            this.btnChonAnh.ForeColor = System.Drawing.Color.White; // Style Change
            this.btnChonAnh.Location = new System.Drawing.Point(426, 375);
            this.btnChonAnh.Name = "btnChonAnh";
            this.btnChonAnh.Size = new System.Drawing.Size(90, 30); // Style Change: Chiều cao đồng bộ
            this.btnChonAnh.TabIndex = 24;
            this.btnChonAnh.Text = "Chọn ảnh";
            this.btnChonAnh.UseVisualStyleBackColor = false; // Style Change
            // 
            // picHinhAnhSanPham
            // 
            this.picHinhAnhSanPham.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(230)))), ((int)(((byte)(230))))); // Style Change: Nền nhẹ cho ảnh
            this.picHinhAnhSanPham.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.picHinhAnhSanPham.Location = new System.Drawing.Point(130, 410);
            this.picHinhAnhSanPham.Name = "picHinhAnhSanPham";
            this.picHinhAnhSanPham.Size = new System.Drawing.Size(150, 150);
            this.picHinhAnhSanPham.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.picHinhAnhSanPham.TabIndex = 23;
            this.picHinhAnhSanPham.TabStop = false;
            // 
            // txtHinhAnhUrl
            // 
            this.txtHinhAnhUrl.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtHinhAnhUrl.Font = new System.Drawing.Font("Segoe UI", 9F); // Style Change
            this.txtHinhAnhUrl.Location = new System.Drawing.Point(130, 378);
            this.txtHinhAnhUrl.Name = "txtHinhAnhUrl";
            this.txtHinhAnhUrl.Size = new System.Drawing.Size(290, 27); // Style Change
            this.txtHinhAnhUrl.TabIndex = 22;
            // 
            // label13
            // 
            this.label13.AutoSize = true;
            this.label13.Font = new System.Drawing.Font("Segoe UI", 9F); // Style Change
            this.label13.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64))))); // Style Change: Màu chữ thường
            this.label13.Location = new System.Drawing.Point(20, 381);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(99, 20); // Style Change
            this.label13.TabIndex = 21;
            this.label13.Text = "URL Hình ảnh:";
            // 
            // txtNgayCapNhat
            // 
            this.txtNgayCapNhat.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) | System.Windows.Forms.AnchorStyles.Right)));
            this.txtNgayCapNhat.Font = new System.Drawing.Font("Segoe UI", 9F); // Style Change
            this.txtNgayCapNhat.Location = new System.Drawing.Point(380, 566); // Điều chỉnh vị trí
            this.txtNgayCapNhat.Name = "txtNgayCapNhat";
            this.txtNgayCapNhat.ReadOnly = true;
            this.txtNgayCapNhat.Size = new System.Drawing.Size(155, 27); // Style Change
            this.txtNgayCapNhat.TabIndex = 20;
            // 
            // label12
            // 
            this.label12.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.label12.AutoSize = true;
            this.label12.Font = new System.Drawing.Font("Segoe UI", 9F); // Style Change
            this.label12.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64))))); // Style Change: Màu chữ thường
            this.label12.Location = new System.Drawing.Point(270, 569); // Điều chỉnh vị trí
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(107, 20); // Style Change
            this.label12.TabIndex = 19;
            this.label12.Text = "Ngày cập nhật:";
            // 
            // txtNgayTao
            // 
            this.txtNgayTao.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.txtNgayTao.Font = new System.Drawing.Font("Segoe UI", 9F); // Style Change
            this.txtNgayTao.Location = new System.Drawing.Point(100, 566); // Điều chỉnh vị trí
            this.txtNgayTao.Name = "txtNgayTao";
            this.txtNgayTao.ReadOnly = true;
            this.txtNgayTao.Size = new System.Drawing.Size(155, 27); // Style Change
            this.txtNgayTao.TabIndex = 18;
            // 
            // label11
            // 
            this.label11.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.label11.AutoSize = true;
            this.label11.Font = new System.Drawing.Font("Segoe UI", 9F); // Style Change
            this.label11.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64))))); // Style Change: Màu chữ thường
            this.label11.Location = new System.Drawing.Point(20, 569); // Điều chỉnh vị trí
            this.label11.Name = "label11";
            this.label11.Size = new System.Drawing.Size(72, 20); // Style Change
            this.label11.TabIndex = 17;
            this.label11.Text = "Ngày tạo:";
            // 
            // radInactive
            // 
            this.radInactive.AutoSize = true;
            this.radInactive.Font = new System.Drawing.Font("Segoe UI", 9F); // Style Change
            this.radInactive.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64))))); // Style Change: Màu chữ thường
            this.radInactive.Location = new System.Drawing.Point(220, 340);
            this.radInactive.Name = "radInactive";
            this.radInactive.Size = new System.Drawing.Size(78, 24); // Style Change
            this.radInactive.TabIndex = 16;
            this.radInactive.Text = "Inactive";
            this.radInactive.UseVisualStyleBackColor = true;
            // 
            // radActive
            // 
            this.radActive.AutoSize = true;
            this.radActive.Checked = true;
            this.radActive.Font = new System.Drawing.Font("Segoe UI", 9F); // Style Change
            this.radActive.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64))))); // Style Change: Màu chữ thường
            this.radActive.Location = new System.Drawing.Point(130, 340);
            this.radActive.Name = "radActive";
            this.radActive.Size = new System.Drawing.Size(69, 24); // Style Change
            this.radActive.TabIndex = 15;
            this.radActive.TabStop = true;
            this.radActive.Text = "Active";
            this.radActive.UseVisualStyleBackColor = true;
            // 
            // label10
            // 
            this.label10.AutoSize = true;
            this.label10.Font = new System.Drawing.Font("Segoe UI", 9F); // Style Change
            this.label10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64))))); // Style Change: Màu chữ thường
            this.label10.Location = new System.Drawing.Point(20, 342);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(112, 20); // Style Change
            this.label10.TabIndex = 14;
            this.label10.Text = "Trạng thái chung:";
            // 
            // cboDonViTinh
            // 
            this.cboDonViTinh.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
            | System.Windows.Forms.AnchorStyles.Right)));
            this.cboDonViTinh.Font = new System.Drawing.Font("Segoe UI", 9F); // Style Change
            this.cboDonViTinh.FormattingEnabled = true;
            this.cboDonViTinh.Location = new System.Drawing.Point(130, 300);
            this.cboDonViTinh.Name = "cboDonViTinh";
            this.cboDonViTinh.Size = new System.Drawing.Size(180, 28); // Style Change
            this.cboDonViTinh.TabIndex = 13;
            // 
            // label9
            // 
            this.label9.AutoSize = true;
            this.label9.Font = new System.Drawing.Font("Segoe UI", 9F); // Style Change
            this.label9.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64))))); // Style Change: Màu chữ thường
            this.label9.Location = new System.Drawing.Point(20, 303);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(79, 20); // Style Change
            this.label9.TabIndex = 12;
            this.label9.Text = "Đơn vị tính:";
            // 
            // numGiaKhuyenNghi
            // 
            this.numGiaKhuyenNghi.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
            | System.Windows.Forms.AnchorStyles.Right)));
            this.numGiaKhuyenNghi.DecimalPlaces = 0; // Style Change: Bỏ số lẻ nếu giá thường là số chẵn VNĐ
            this.numGiaKhuyenNghi.Font = new System.Drawing.Font("Segoe UI", 9F); // Style Change
            this.numGiaKhuyenNghi.Location = new System.Drawing.Point(130, 265);
            this.numGiaKhuyenNghi.Maximum = new decimal(new int[] {
            100000000,
            0,
            0,
            0});
            this.numGiaKhuyenNghi.Name = "numGiaKhuyenNghi";
            this.numGiaKhuyenNghi.Size = new System.Drawing.Size(180, 27); // Style Change
            this.numGiaKhuyenNghi.TabIndex = 11;
            this.numGiaKhuyenNghi.ThousandsSeparator = true;
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("Segoe UI", 9F); // Style Change
            this.label8.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64))))); // Style Change: Màu chữ thường
            this.label8.Location = new System.Drawing.Point(20, 267);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(112, 20); // Style Change
            this.label8.TabIndex = 10;
            this.label8.Text = "Giá khuyến nghị:";
            // 
            // cboDanhMuc
            // 
            this.cboDanhMuc.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
            | System.Windows.Forms.AnchorStyles.Right)));
            this.cboDanhMuc.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboDanhMuc.Font = new System.Drawing.Font("Segoe UI", 9F); // Style Change
            this.cboDanhMuc.FormattingEnabled = true;
            this.cboDanhMuc.Location = new System.Drawing.Point(130, 230);
            this.cboDanhMuc.Name = "cboDanhMuc";
            this.cboDanhMuc.Size = new System.Drawing.Size(290, 28); // Style Change
            this.cboDanhMuc.TabIndex = 9;
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Segoe UI", 9F); // Style Change
            this.label7.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64))))); // Style Change: Màu chữ thường
            this.label7.Location = new System.Drawing.Point(20, 233);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(78, 20); // Style Change
            this.label7.TabIndex = 8;
            this.label7.Text = "Danh mục:";
            // 
            // txtMoTa
            // 
            this.txtMoTa.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtMoTa.Font = new System.Drawing.Font("Segoe UI", 9F); // Style Change
            this.txtMoTa.Location = new System.Drawing.Point(130, 145);
            this.txtMoTa.Multiline = true;
            this.txtMoTa.Name = "txtMoTa";
            this.txtMoTa.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.txtMoTa.Size = new System.Drawing.Size(390, 75);
            this.txtMoTa.TabIndex = 7;
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Segoe UI", 9F); // Style Change
            this.label6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64))))); // Style Change: Màu chữ thường
            this.label6.Location = new System.Drawing.Point(20, 148);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(51, 20); // Style Change
            this.label6.TabIndex = 6;
            this.label6.Text = "Mô tả:";
            // 
            // txtTenSanPham
            // 
            this.txtTenSanPham.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtTenSanPham.Font = new System.Drawing.Font("Segoe UI", 9F); // Style Change
            this.txtTenSanPham.Location = new System.Drawing.Point(130, 110);
            this.txtTenSanPham.Name = "txtTenSanPham";
            this.txtTenSanPham.Size = new System.Drawing.Size(390, 27); // Style Change
            this.txtTenSanPham.TabIndex = 5;
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Segoe UI", 9F); // Style Change
            this.label5.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64))))); // Style Change: Màu chữ thường
            this.label5.Location = new System.Drawing.Point(20, 113);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(100, 20); // Style Change
            this.label5.TabIndex = 4;
            this.label5.Text = "Tên sản phẩm:";
            // 
            // txtMaSanPham
            // 
            this.txtMaSanPham.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)
            | System.Windows.Forms.AnchorStyles.Right)));
            this.txtMaSanPham.Font = new System.Drawing.Font("Segoe UI", 9F); // Style Change
            this.txtMaSanPham.Location = new System.Drawing.Point(130, 75);
            this.txtMaSanPham.Name = "txtMaSanPham";
            this.txtMaSanPham.Size = new System.Drawing.Size(240, 27); // Style Change
            this.txtMaSanPham.TabIndex = 3;
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Segoe UI", 9F); // Style Change
            this.label4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64))))); // Style Change: Màu chữ thường
            this.label4.Location = new System.Drawing.Point(20, 78);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(98, 20); // Style Change
            this.label4.TabIndex = 2;
            this.label4.Text = "Mã sản phẩm:";
            // 
            // txtIdSanPham
            // 
            this.txtIdSanPham.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224))))); // Style Change: Nền xám nhẹ cho ReadOnly
            this.txtIdSanPham.Font = new System.Drawing.Font("Segoe UI", 9F); // Style Change
            this.txtIdSanPham.Location = new System.Drawing.Point(130, 40);
            this.txtIdSanPham.Name = "txtIdSanPham";
            this.txtIdSanPham.ReadOnly = true;
            this.txtIdSanPham.Size = new System.Drawing.Size(100, 27); // Style Change
            this.txtIdSanPham.TabIndex = 1;
            // 
            // lblId
            // 
            this.lblId.AutoSize = true;
            this.lblId.Font = new System.Drawing.Font("Segoe UI", 9F); // Style Change
            this.lblId.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64))))); // Style Change: Màu chữ thường
            this.lblId.Location = new System.Drawing.Point(20, 43);
            this.lblId.Name = "lblId";
            this.lblId.Size = new System.Drawing.Size(91, 20); // Style Change
            this.lblId.TabIndex = 0;
            this.lblId.Text = "ID Sản phẩm:";
            // 
            // panelNutChucNang
            // 
            this.panelNutChucNang.BackColor = System.Drawing.Color.White; // Style Change
            this.panelNutChucNang.Controls.Add(this.btnBoQua);
            this.panelNutChucNang.Controls.Add(this.btnXoa);
            this.panelNutChucNang.Controls.Add(this.btnLuu);
            this.panelNutChucNang.Controls.Add(this.btnThemMoi);
            this.panelNutChucNang.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panelNutChucNang.Location = new System.Drawing.Point(0, 600);
            this.panelNutChucNang.Name = "panelNutChucNang";
            this.panelNutChucNang.Padding = new System.Windows.Forms.Padding(0, 5, 0, 5); // Style Change: Padding
            this.panelNutChucNang.Size = new System.Drawing.Size(540, 50);
            this.panelNutChucNang.TabIndex = 1;
            // 
            // btnBoQua
            // 
            this.btnBoQua.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnBoQua.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(108)))), ((int)(((byte)(117)))), ((int)(((byte)(125))))); // Style Change: Màu xám
            this.btnBoQua.FlatAppearance.BorderSize = 0; // Style Change
            this.btnBoQua.FlatStyle = System.Windows.Forms.FlatStyle.Flat; // Style Change
            this.btnBoQua.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold); // Style Change
            this.btnBoQua.ForeColor = System.Drawing.Color.White; // Style Change
            this.btnBoQua.Location = new System.Drawing.Point(435, 10);
            this.btnBoQua.Name = "btnBoQua";
            this.btnBoQua.Size = new System.Drawing.Size(90, 30);
            this.btnBoQua.TabIndex = 3;
            this.btnBoQua.Text = "Bỏ qua";
            this.btnBoQua.UseVisualStyleBackColor = false; // Style Change
            // 
            // btnXoa
            // 
            this.btnXoa.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnXoa.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(83)))), ((int)(((byte)(79))))); // Style Change: Màu đỏ
            this.btnXoa.FlatAppearance.BorderSize = 0; // Style Change
            this.btnXoa.FlatStyle = System.Windows.Forms.FlatStyle.Flat; // Style Change
            this.btnXoa.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold); // Style Change
            this.btnXoa.ForeColor = System.Drawing.Color.White; // Style Change
            this.btnXoa.Location = new System.Drawing.Point(330, 10);
            this.btnXoa.Name = "btnXoa";
            this.btnXoa.Size = new System.Drawing.Size(90, 30);
            this.btnXoa.TabIndex = 2;
            this.btnXoa.Text = "Xóa/Hủy";
            this.btnXoa.UseVisualStyleBackColor = false; // Style Change
            // 
            // btnLuu
            // 
            this.btnLuu.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(123)))), ((int)(((byte)(255))))); // Style Change: Màu xanh dương chính
            this.btnLuu.FlatAppearance.BorderSize = 0; // Style Change
            this.btnLuu.FlatStyle = System.Windows.Forms.FlatStyle.Flat; // Style Change
            this.btnLuu.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold); // Style Change
            this.btnLuu.ForeColor = System.Drawing.Color.White; // Style Change
            this.btnLuu.Location = new System.Drawing.Point(125, 10);
            this.btnLuu.Name = "btnLuu";
            this.btnLuu.Size = new System.Drawing.Size(90, 30);
            this.btnLuu.TabIndex = 1;
            this.btnLuu.Text = "Lưu";
            this.btnLuu.UseVisualStyleBackColor = false; // Style Change
            // 
            // btnThemMoi
            // 
            this.btnThemMoi.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(23)))), ((int)(((byte)(162)))), ((int)(((byte)(184))))); // Style Change: Màu xanh ngọc
            this.btnThemMoi.FlatAppearance.BorderSize = 0; // Style Change
            this.btnThemMoi.FlatStyle = System.Windows.Forms.FlatStyle.Flat; // Style Change
            this.btnThemMoi.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold); // Style Change
            this.btnThemMoi.ForeColor = System.Drawing.Color.White; // Style Change
            this.btnThemMoi.Location = new System.Drawing.Point(20, 10);
            this.btnThemMoi.Name = "btnThemMoi";
            this.btnThemMoi.Size = new System.Drawing.Size(90, 30);
            this.btnThemMoi.TabIndex = 0;
            this.btnThemMoi.Text = "Thêm mới";
            this.btnThemMoi.UseVisualStyleBackColor = false; // Style Change
            // 
            // FormSanPham
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240))))); // Style Change: Nền UserControl
            this.Controls.Add(this.splitContainerMain);
            this.Name = "FormSanPham";
            this.Size = new System.Drawing.Size(1100, 650);
            this.splitContainerMain.Panel1.ResumeLayout(false);
            this.splitContainerMain.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.splitContainerMain)).EndInit();
            this.splitContainerMain.ResumeLayout(false);
            this.panelDanhSach.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dgvDanhSachSanPham)).EndInit();
            this.panelTimKiem.ResumeLayout(false);
            this.panelTimKiem.PerformLayout();
            this.gbChiTietSanPham.ResumeLayout(false);
            this.gbChiTietSanPham.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picHinhAnhSanPham)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numGiaKhuyenNghi)).EndInit();
            this.panelNutChucNang.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.SplitContainer splitContainerMain;
        private System.Windows.Forms.Panel panelDanhSach;
        private System.Windows.Forms.DataGridView dgvDanhSachSanPham;
        private System.Windows.Forms.Panel panelTimKiem;
        private System.Windows.Forms.Button btnLamMoiDanhSach;
        private System.Windows.Forms.Button btnTimKiem;
        private System.Windows.Forms.ComboBox cboLocTrangThai;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.ComboBox cboLocDanhMuc;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.TextBox txtTimKiem;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.GroupBox gbChiTietSanPham;
        private System.Windows.Forms.Button btnChonAnh;
        private System.Windows.Forms.PictureBox picHinhAnhSanPham;
        private System.Windows.Forms.TextBox txtHinhAnhUrl;
        private System.Windows.Forms.Label label13;
        private System.Windows.Forms.TextBox txtNgayCapNhat;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.TextBox txtNgayTao;
        private System.Windows.Forms.Label label11;
        private System.Windows.Forms.RadioButton radInactive;
        private System.Windows.Forms.RadioButton radActive;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.ComboBox cboDonViTinh;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.NumericUpDown numGiaKhuyenNghi;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.ComboBox cboDanhMuc;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.TextBox txtMoTa;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.TextBox txtTenSanPham;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.TextBox txtMaSanPham;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.TextBox txtIdSanPham;
        private System.Windows.Forms.Label lblId;
        private System.Windows.Forms.Panel panelNutChucNang;
        private System.Windows.Forms.Button btnBoQua;
        private System.Windows.Forms.Button btnXoa;
        private System.Windows.Forms.Button btnLuu;
        private System.Windows.Forms.Button btnThemMoi;
        private System.Windows.Forms.DataGridViewTextBoxColumn maSanPhamCol;
        private System.Windows.Forms.DataGridViewTextBoxColumn tenSanPhamCol;
        private System.Windows.Forms.DataGridViewTextBoxColumn danhMucCol;
        private System.Windows.Forms.DataGridViewTextBoxColumn giaKhuyenNghiCol;
        private System.Windows.Forms.DataGridViewTextBoxColumn donViTinhCol;
        private System.Windows.Forms.DataGridViewTextBoxColumn trangThaiChungCol;
    }
}